/* Generated by npm run locales; edit the _locales JSON files instead. */
(function(root) {
    const dictionaries = {
  "en": {
    "extName": {
      "message": "YouTube Feed Cleaner"
    },
    "extDesc": {
      "message": "Precisely filter YouTube Mixes, Shorts, watched videos, titles and channels. GitHub update notifications."
    },
    "enabled": {
      "message": "Enable filtering"
    },
    "filtersTab": {
      "message": "Filters"
    },
    "contentTypes": {
      "message": "Content types"
    },
    "optHideJams": {
      "message": "Hide Mixes (all pages)"
    },
    "optHideShortsHome": {
      "message": "Shorts on Home"
    },
    "optHideShortsSearch": {
      "message": "Shorts in Search"
    },
    "shortsOther": {
      "message": "Shorts on other pages"
    },
    "videoFilters": {
      "message": "Video filters"
    },
    "scopeHint": {
      "message": "Apply the filters below to:"
    },
    "home": {
      "message": "Home"
    },
    "search": {
      "message": "Search"
    },
    "recommendations": {
      "message": "Recommendations"
    },
    "subscriptions": {
      "message": "Subscriptions"
    },
    "optHideWatched": {
      "message": "Hide watched videos"
    },
    "lblWatchThreshold": {
      "message": "Watch threshold: $VALUE$%",
      "placeholders": {
        "value": {
          "content": "$1"
        }
      }
    },
    "ageDays": {
      "message": "Hide older than (days; 0 = off)"
    },
    "minDuration": {
      "message": "Minimum minutes (0 = off)"
    },
    "maxDuration": {
      "message": "Maximum minutes (0 = off)"
    },
    "hideLive": {
      "message": "Hide live streams"
    },
    "hideUpcoming": {
      "message": "Hide upcoming premieres"
    },
    "hidePlaylists": {
      "message": "Hide regular playlists"
    },
    "customRules": {
      "message": "Titles and channels"
    },
    "titleKeywords": {
      "message": "Hide titles containing"
    },
    "keywordsHint": {
      "message": "One phrase per line, case-insensitive."
    },
    "blockedChannels": {
      "message": "Hide channels"
    },
    "allowedChannels": {
      "message": "Never hide channels"
    },
    "channelsHint": {
      "message": "One exact name, @handle or channel URL per line."
    },
    "safeHint": {
      "message": "Unknown metadata never triggers a filter. Age: English/Russian publication labels only; conservative month estimates. Duration bounds are inclusive."
    },
    "updates": {
      "message": "GitHub updates"
    },
    "notifications": {
      "message": "Desktop notifications"
    },
    "trackCommits": {
      "message": "Also notify about new commits"
    },
    "checkNow": {
      "message": "Check now"
    },
    "dismissUpdates": {
      "message": "Mark as seen"
    },
    "manualUpdate": {
      "message": "Checks every 6 hours. Updates are installed manually; a commit is not a released version. The first check establishes the commit baseline."
    },
    "githubLink": {
      "message": "Source on GitHub"
    },
    "reset": {
      "message": "Reset filters"
    },
    "resetConfirm": {
      "message": "Restore default filters? Language, appearance and update preferences will be preserved."
    },
    "statsHidden": {
      "message": "Hidden on this page: $COUNT$",
      "placeholders": {
        "count": {
          "content": "$1"
        }
      }
    },
    "whyHidden": {
      "message": "Why were these hidden?"
    },
    "showHidden": {
      "message": "Show hidden temporarily"
    },
    "resumeHiding": {
      "message": "Resume hiding"
    },
    "previewActive": {
      "message": "Preview: everything is visible in this tab"
    },
    "openYouTube": {
      "message": "Open YouTube"
    },
    "reloadYouTube": {
      "message": "Open / reload YouTube to see statistics"
    },
    "saved": {
      "message": "Saved"
    },
    "saveFailed": {
      "message": "Could not save settings"
    },
    "invalidDuration": {
      "message": "Maximum duration must not be less than minimum duration."
    },
    "newVersion": {
      "message": "New version"
    },
    "newCommit": {
      "message": "New commit"
    },
    "updateMsg": {
      "message": "Updates available on GitHub"
    },
    "lastCheck": {
      "message": "Last successful check"
    },
    "notChecked": {
      "message": "No successful check yet"
    },
    "checkFailed": {
      "message": "Check failed"
    },
    "retryAfter": {
      "message": "Retry after"
    },
    "checking": {
      "message": "Checking GitHub…"
    },
    "reason_mix": {
      "message": "Mix"
    },
    "reason_shorts": {
      "message": "Shorts"
    },
    "reason_playlist": {
      "message": "Playlist"
    },
    "reason_live": {
      "message": "Live stream"
    },
    "reason_upcoming": {
      "message": "Upcoming premiere"
    },
    "reason_watched": {
      "message": "Watch progress"
    },
    "reason_age": {
      "message": "Publication age"
    },
    "reason_short_duration": {
      "message": "Below minimum duration"
    },
    "reason_long_duration": {
      "message": "Above maximum duration"
    },
    "reason_keyword": {
      "message": "Title phrase"
    },
    "reason_channel": {
      "message": "Blocked channel"
    },
    "appTitle": {
      "message": "YouTube Cleaner"
    },
    "updatesTab": {
      "message": "Updates"
    },
    "appearanceTab": {
      "message": "Appearance"
    },
    "appearanceTitle": {
      "message": "Settings"
    },
    "languageLabel": {
      "message": "Interface language"
    },
    "languageAuto": {
      "message": "Automatic (browser language)"
    },
    "languageRussian": {
      "message": "Русский (Russian)"
    },
    "languageEnglish": {
      "message": "English"
    },
    "textSizeLabel": {
      "message": "Text size"
    },
    "textNormal": {
      "message": "Standard — 16 px"
    },
    "textLarge": {
      "message": "Large — 18 px"
    },
    "textExtra": {
      "message": "Extra large — 20 px"
    },
    "animateHidingLabel": {
      "message": "Disintegrate videos when hiding"
    },
    "animationSpeedLabel": {
      "message": "Disintegration speed"
    },
    "animationFast": {
      "message": "Fast — 0.45 s"
    },
    "animationNormal": {
      "message": "Normal — 0.8 s"
    },
    "animationSlow": {
      "message": "Slow — 1.2 s"
    },
    "respectReducedMotionLabel": {
      "message": "Respect reduced motion in the OS"
    },
    "animationHint": {
      "message": "Animation is off by default. Only visible cards dissolve into particles; other cards hide immediately. Disabling a filter or showing hidden cards cancels the effect immediately."
    },
    "motionHint": {
      "message": "The effect is skipped when the OS requests reduced motion. Turn this setting off to allow the effect regardless of the OS preference."
    },
    "appearanceHint": {
      "message": "Language changes immediately and also applies to notifications. Text size affects this settings window. All filters and the master switch remain on the Filters tab."
    },
    "iconHint": {
      "message": "The interface uses SVG. Chrome requires PNG copies for the extension toolbar and desktop notifications."
    },
    "badgeNew": {
      "message": "NEW"
    },
    "httpError": {
      "message": "GitHub returned HTTP $CODE$",
      "placeholders": {
        "code": {
          "content": "$1"
        }
      }
    },
    "networkError": {
      "message": "Cannot reach GitHub. Check your connection."
    },
    "timeoutError": {
      "message": "GitHub did not respond in time."
    },
    "invalidResponse": {
      "message": "GitHub returned invalid data."
    },
    "operationError": {
      "message": "The operation failed. Please try again."
    },
    "downloadRelease": {
      "message": "Download latest release"
    },
    "refreshStats": {
      "message": "Refresh"
    },
    "reconnectStats": {
      "message": "Connect"
    },
    "connectionFailed": {
      "message": "Cannot connect to the YouTube tab."
    },
    "replayAnimation": {
      "message": "Replay effect"
    },
    "animation_off": {
      "message": "Animation off"
    },
    "animation_on": {
      "message": "Animation on"
    },
    "animation_reduced": {
      "message": "Animation disabled by the OS preference"
    },
    "animation_background": {
      "message": "The effect starts when you return to YouTube"
    }
  },
  "ru": {
    "extName": {
      "message": "Очистка ленты YouTube"
    },
    "extDesc": {
      "message": "Точные фильтры YouTube: джемы, Shorts, просмотренные видео, заголовки и каналы. Оповещения об обновлениях GitHub."
    },
    "enabled": {
      "message": "Включить фильтрацию"
    },
    "filtersTab": {
      "message": "Фильтры"
    },
    "contentTypes": {
      "message": "Типы контента"
    },
    "optHideJams": {
      "message": "Скрывать джемы (на всех страницах)"
    },
    "optHideShortsHome": {
      "message": "Shorts на Главной"
    },
    "optHideShortsSearch": {
      "message": "Shorts в Поиске"
    },
    "shortsOther": {
      "message": "Shorts на остальных страницах"
    },
    "videoFilters": {
      "message": "Фильтры видео"
    },
    "scopeHint": {
      "message": "Применять фильтры ниже к разделам:"
    },
    "home": {
      "message": "Главная"
    },
    "search": {
      "message": "Поиск"
    },
    "recommendations": {
      "message": "Рекомендации"
    },
    "subscriptions": {
      "message": "Подписки"
    },
    "optHideWatched": {
      "message": "Скрывать просмотренные видео"
    },
    "lblWatchThreshold": {
      "message": "Порог просмотра: $VALUE$%",
      "placeholders": {
        "value": {
          "content": "$1"
        }
      }
    },
    "ageDays": {
      "message": "Скрывать старше (дней; 0 = выключено)"
    },
    "minDuration": {
      "message": "Минимум минут (0 = выкл.)"
    },
    "maxDuration": {
      "message": "Максимум минут (0 = выкл.)"
    },
    "hideLive": {
      "message": "Скрывать прямые эфиры"
    },
    "hideUpcoming": {
      "message": "Скрывать ожидаемые премьеры"
    },
    "hidePlaylists": {
      "message": "Скрывать обычные плейлисты"
    },
    "customRules": {
      "message": "Заголовки и каналы"
    },
    "titleKeywords": {
      "message": "Скрывать заголовки с фразами"
    },
    "keywordsHint": {
      "message": "Одна фраза на строку, без учёта регистра."
    },
    "blockedChannels": {
      "message": "Скрывать каналы"
    },
    "allowedChannels": {
      "message": "Никогда не скрывать каналы"
    },
    "channelsHint": {
      "message": "Точное имя, @псевдоним или URL — по одному на строку."
    },
    "safeHint": {
      "message": "Неизвестные метаданные не вызывают скрытие. Возраст — только по дате публикации на русском/английском; месяцы оцениваются консервативно. Границы длительности включены."
    },
    "updates": {
      "message": "Обновления GitHub"
    },
    "notifications": {
      "message": "Системные уведомления"
    },
    "trackCommits": {
      "message": "Сообщать и о новых коммитах"
    },
    "checkNow": {
      "message": "Проверить сейчас"
    },
    "dismissUpdates": {
      "message": "Отметить прочитанным"
    },
    "manualUpdate": {
      "message": "Проверка раз в 6 часов. Установка вручную; коммит — не новая выпущенная версия. Первая проверка запоминает исходный коммит."
    },
    "githubLink": {
      "message": "Исходники на GitHub"
    },
    "reset": {
      "message": "Сбросить фильтры"
    },
    "resetConfirm": {
      "message": "Восстановить стандартные фильтры? Язык, оформление и настройки оповещений сохранятся."
    },
    "statsHidden": {
      "message": "Скрыто на странице: $COUNT$",
      "placeholders": {
        "count": {
          "content": "$1"
        }
      }
    },
    "whyHidden": {
      "message": "Почему это скрыто?"
    },
    "showHidden": {
      "message": "Временно показать скрытое"
    },
    "resumeHiding": {
      "message": "Возобновить скрытие"
    },
    "previewActive": {
      "message": "Просмотр: в этой вкладке всё показано"
    },
    "openYouTube": {
      "message": "Откройте YouTube"
    },
    "reloadYouTube": {
      "message": "Откройте / перезагрузите YouTube для статистики"
    },
    "saved": {
      "message": "Сохранено"
    },
    "saveFailed": {
      "message": "Не удалось сохранить настройки"
    },
    "invalidDuration": {
      "message": "Максимальная длительность не должна быть меньше минимальной."
    },
    "newVersion": {
      "message": "Новая версия"
    },
    "newCommit": {
      "message": "Новый коммит"
    },
    "updateMsg": {
      "message": "На GitHub доступны обновления"
    },
    "lastCheck": {
      "message": "Последняя успешная проверка"
    },
    "notChecked": {
      "message": "Успешных проверок ещё не было"
    },
    "checkFailed": {
      "message": "Ошибка проверки"
    },
    "retryAfter": {
      "message": "Повторить после"
    },
    "checking": {
      "message": "Проверяем GitHub…"
    },
    "reason_mix": {
      "message": "Джем"
    },
    "reason_shorts": {
      "message": "Shorts"
    },
    "reason_playlist": {
      "message": "Плейлист"
    },
    "reason_live": {
      "message": "Прямой эфир"
    },
    "reason_upcoming": {
      "message": "Ожидаемая премьера"
    },
    "reason_watched": {
      "message": "Прогресс просмотра"
    },
    "reason_age": {
      "message": "Возраст публикации"
    },
    "reason_short_duration": {
      "message": "Короче минимума"
    },
    "reason_long_duration": {
      "message": "Длиннее максимума"
    },
    "reason_keyword": {
      "message": "Фраза в заголовке"
    },
    "reason_channel": {
      "message": "Заблокированный канал"
    },
    "appTitle": {
      "message": "Очистка YouTube"
    },
    "updatesTab": {
      "message": "Обновления"
    },
    "appearanceTab": {
      "message": "Интерфейс"
    },
    "appearanceTitle": {
      "message": "Настройки"
    },
    "languageLabel": {
      "message": "Язык интерфейса"
    },
    "languageAuto": {
      "message": "Автоматически (язык браузера)"
    },
    "languageRussian": {
      "message": "Русский"
    },
    "languageEnglish": {
      "message": "English (английский)"
    },
    "textSizeLabel": {
      "message": "Размер текста"
    },
    "textNormal": {
      "message": "Обычный — 16 px"
    },
    "textLarge": {
      "message": "Крупный — 18 px"
    },
    "textExtra": {
      "message": "Очень крупный — 20 px"
    },
    "animateHidingLabel": {
      "message": "Распыление скрываемых видео"
    },
    "animationSpeedLabel": {
      "message": "Скорость распыления"
    },
    "animationFast": {
      "message": "Быстро — 0,45 с"
    },
    "animationNormal": {
      "message": "Обычно — 0,8 с"
    },
    "animationSlow": {
      "message": "Медленно — 1,2 с"
    },
    "respectReducedMotionLabel": {
      "message": "Учитывать запрет анимаций в ОС"
    },
    "animationHint": {
      "message": "Анимация выключена по умолчанию. Только видимые карточки распадаются на частицы; остальные скрываются сразу. Выключение фильтра или показ скрытого немедленно отменяет эффект."
    },
    "motionHint": {
      "message": "Если в ОС включено уменьшение движения, эффект не запускается. При выключении этой настройки эффект разрешён независимо от ОС."
    },
    "appearanceHint": {
      "message": "Язык меняется сразу и используется в оповещениях. Размер текста относится к окну настроек. Все фильтры и общий выключатель остаются на вкладке «Фильтры»."
    },
    "iconHint": {
      "message": "В интерфейсе используется SVG. Chrome требует PNG-копии для панели расширений и системных уведомлений."
    },
    "badgeNew": {
      "message": "НОВ"
    },
    "httpError": {
      "message": "GitHub вернул HTTP $CODE$",
      "placeholders": {
        "code": {
          "content": "$1"
        }
      }
    },
    "networkError": {
      "message": "Нет связи с GitHub. Проверьте подключение."
    },
    "timeoutError": {
      "message": "GitHub не ответил вовремя."
    },
    "invalidResponse": {
      "message": "GitHub вернул некорректные данные."
    },
    "operationError": {
      "message": "Операция не выполнена. Попробуйте ещё раз."
    },
    "downloadRelease": {
      "message": "Скачать последний релиз"
    },
    "refreshStats": {
      "message": "Обновить"
    },
    "reconnectStats": {
      "message": "Подключить"
    },
    "connectionFailed": {
      "message": "Нет связи со вкладкой YouTube."
    },
    "replayAnimation": {
      "message": "Повторить эффект"
    },
    "animation_off": {
      "message": "Анимация выключена"
    },
    "animation_on": {
      "message": "Анимация включена"
    },
    "animation_reduced": {
      "message": "Анимация отключена настройкой ОС"
    },
    "animation_background": {
      "message": "Эффект начнётся при переходе на YouTube"
    }
  }
};
    root.YTFCTranslations = dictionaries;
    if (typeof module !== 'undefined' && module.exports) module.exports = dictionaries;
})(globalThis);
