// Browser and worker translations are generated from Chrome's canonical locale files.
const fs = require('node:fs');
const path = require('node:path');
const dictionaries = Object.fromEntries(['en', 'ru'].map(language => [language, JSON.parse(fs.readFileSync(path.join(__dirname, `../_locales/${language}/messages.json`), 'utf8'))]));
if (JSON.stringify(Object.keys(dictionaries.en).sort()) !== JSON.stringify(Object.keys(dictionaries.ru).sort())) throw new Error('Locale keys differ');
const output = `/* Generated by npm run locales; edit the _locales JSON files instead. */\n(function(root) {\n    const dictionaries = ${JSON.stringify(dictionaries, null, 2)};\n    root.YTFCTranslations = dictionaries;\n    if (typeof module !== 'undefined' && module.exports) module.exports = dictionaries;\n})(globalThis);\n`;
fs.writeFileSync(path.join(__dirname, '../translations.js'), output);
